#!/usr/bin/env python2

#remember to install:
# requests: \http://docs.python-requests.org/en/latest/user/quickstart/
# RFM69 library: https://github.com/etrombly/RFM69
# modify RFM69.py for properly rstPin (28 not good)

import RFM69
from RFM69registers import *
import requests
import time

sink = "http://bars.slartitorto.eu/datasink2.php"
router_name = "000029"
rf69 = RFM69.RFM69(RF69_433MHZ, 1, 0, True)
rf69.rcCalibration()
while True:
    rf69.receiveBegin()
    while not rf69.receiveDone():
        time.sleep(.1)
    # print(rf69.DATA)
    rssi=(100+(((rf69.RSSI)+28)*100/72))
    payload = ("".join([chr(letter) for letter in rf69.DATA]))
    # print "%s from %s RSSI:%s" % (payload,rf69.SENDERID, rssi)
    url = sink + '?data=' + payload
    other_data = {'rssi':rssi,'router':router_name}
    requests.get(url,params=other_data,stream=True)
